export { default as IconMilkDairies } from "../IconMilkDairies.vue"
export { default as IconDrinks } from "../icons/IconDrinks.vue"
export { default as IconClothes } from "../icons/IconClothes.vue"
export { default as IconPetFoods } from "../icons/IconPetFoods.vue"
export { default as IconPackagedFood } from "../icons/IconPackagedFood.vue"
export { default as IconBaking } from "../icons/IconBaking.vue"
export { default as IconVegetables } from "../icons/IconVegetables.vue"
export { default as IconFreshSeafood } from "../icons/IconFreshSeafood.vue"